name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Lefixi/deploy_docker_npm@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "deploy-docker-esgi"
          heroku_email: "dfleboss@gmail.com"
          usedocker: true  // make sure to be true
          docker_build_args: |
            NODE_ENV
        env:
          NODE_ENV: production
          SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
